# ops/monitoring/prometheus.yml

# Global settings
global:
  scrape_interval: 15s

# Define your scrape targets
scrape_configs:
  # Prometheus self-monitoring
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Host metrics from node_exporter
  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]
