# ops/monitoring/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus self‑monitoring
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Host metrics from node_exporter
  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]

  # Docker container metrics via cAdvisor
  - job_name: cadvisor
    static_configs:
      - targets: ["localhost:8080"]
